cart/urls.py
from django.urls import path 
from .import views
app_name ="cart"

urlpatterns =[
	path('', views.Cart, name="cart"),
	path('add-to-cart/<int:pk>', views.add_to_cart, name="add-to-cart"),
	path('remove-from-cart/<int:pk>', views.remove_from_cart, name="remove-from-cart"),
	path('pay-btn', views.payButton, name="pay-btn"),

	path("checkout", views.checkoutPage, name="checkout"),
]

courses/urls.py
from django.urls import path
from .import views
app_name = 'courses'

urlpatterns=[
    path('', views.index, name="homepage"),
    path('list-courses', views.listCoursesView, name="list-courses"),
    path('course-detail/<int:pk>', views.CourseDetailView, name="course-detail"),

    # user specific screens
    path("my-account", views.userAccountPage, name="account"),
    path("list-lessons", views.userRegisteredCourses.as_view(),name="list-lessons"),
    path("lesson/<int:pk>", views.userLessonsPage, name="lesson"),

    path("upload-course", views.uploadCourse, name="upload-course"),
    path("upload-episodes/<int:pk>", views.uploadEpisodes, name="upload-episodes"),

    path('delete-course/<int:pk>', views.deleteCourse, name='delete-course'),
    
    path("my-uploaded-courses-list", views.myUploadedCoursesList, name="my-uploaded-courses")
]

udemyClone/urls.py
"""udemyClone URL Configuration
"""

from django.contrib import admin
from django.urls import path, include
from courses import views
from udemyClone import settings

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls')),
    path('register/', include('register.urls')),
    path('cart/', include("cart.urls")),
    path('', include('django.contrib.auth.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
from django.db import models
from django.contrib.auth import get_user_model 

User = get_user_model()

# Create your models here.
class Rate(models.Model):
	rate_number  		= models.IntegerField()


class CourseSection(models.Model):
	section_title  		= models.CharField(max_length=225,blank=True,null=True)
	section_number  	= models.IntegerField(blank=True,null=True)
	episodes  			= models.ManyToManyField('Episode',blank=True)

	def total_length(self):
		total=Decimal(0.00)
		for episode in self.episodes.all():
			total+=episode.length
		return get_timer(total,type='min')


class Comment(models.Model):
	user  			= models.ForeignKey(User,on_delete=models.CASCADE)
	message  		= models.CharField(max_length=225)
	created  		= models.DateTimeField(auto_now=True)



class Courses(models.Model):
	title			= models.CharField(max_length=225)
	description		= models.CharField(max_length=225)
	created			= models.DateTimeField(auto_now_add=True)
	updated			= models.DateTimeField(auto_now=True)
	rating 			= models.ManyToManyField('Rate',blank=True)
	author  		= models.ForeignKey(User, on_delete=models.CASCADE)
	student_rating	= models.IntegerField(default=0)
	language  		= models.CharField(max_length=225)
	course_length  	= models.CharField(default=0,max_length=20)
	course_sections = models.ManyToManyField('CourseSection',blank=True)
	comment  		= models.ManyToManyField('Comment',blank=True)
	image  			= models.ImageField()
	free_price 		= models.BooleanField(default=False, verbose_name="Free Course")
	price  			= models.IntegerField()
	discount_price  = models.IntegerField(blank=True, null=True)

	def __str__(self):
		return self.title 
	class Meta:
		verbose_name_plural = "Courses"

class Episode(models.Model):
	title  			= models.CharField(max_length=225)
	file  			= models.FileField()
	length  		= models.IntegerField()
	course 			= models.ForeignKey(Courses, on_delete=models.CASCADE) 	
	description 	= models.CharField(max_length=30)		 

	def get_video_length(self):
		try:
			video=MP4(self.file)
			return video.info.length
			
		except:
			return 0.0

	def get_video_length_time(self):
		return get_timer(self.length)
	
	def get_absolute_url(self):
		return self.file.url

	def __str__(self):
		return self.course.title
	
		
	
	def save(self,*args, **kwargs):
		self.length=self.get_video_length()
		# print(self.length)
		# print(self.file.path)
		
		
		return super().save(*args, **kwargs)

courses/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse
from .models import Courses, Episode
from cart.models import Order
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View
from django.contrib import messages

# Create your views here.

User = get_user_model()

def index(request):
	courses     = Courses.objects.all()
	context = {
		"courses":courses,
		
	}
	return render(request, 'home-1.html', context)

@login_required
def listCoursesView(request):
	courses     = Courses.objects.all()
	context     = {
		"courses":courses
	}
	return render(request, 'list-courses.html', context)

@login_required
def CourseDetailView(request, pk):
	course          = Courses.objects.get(id=pk)
	courseEpisodes  = Episode.objects.filter(course=course.id)
	context         = {
		"course":course,
		"courseEpisodes":courseEpisodes
	}
	return render(request, 'course-detail.html', context)


# User specific screens
@login_required
def userAccountPage(request):
	user            = User.objects.get(id=request.user.id)
	context         = {
		"user":user
	}
	return render(request, 'edit-profile.html', context)


class userRegisteredCourses(LoginRequiredMixin, View):
	def get(self, *args, **kwargs):

		try:
			order = Order.objects.filter(user=self.request.user, ordered=True)
			context = {
				'objects':order
			}
			return render(self.request, 'events.html', context)
		except Order.DoesNotExist:
			return render(self.request, 'events.html')

@login_required
def myUploadedCoursesList(request):
	objects =  Courses.objects.filter(author=request.user)
	context ={
		"objects":objects
	}
	return render(request, 'my-uploaded-course.html', context)

@login_required
def deleteCourse(request, pk):
	course 		= Courses.objects.get(id=pk)
	course.delete()
	messages.success(request, "Course deleted successfully")
	return redirect('courses:my-uploaded-courses')


@login_required
def userLessonsPage(request, pk):
	course          = Courses.objects.get(id=pk)
	courseEpisodes  = Episode.objects.filter(course=course.id)
	try:
		currentPlay  	= Episode.objects.filter(course=course.id).first()
	except:
		currentPlay 	= Episode.objects.filter(course=course.id)

	if request.method=="POST":
		course          = Courses.objects.get(id=pk)
		courseEpisodes  = Episode.objects.filter(course=course.id)
		currentPlay 	= Episode.objects.get(course=course.id, id=request.POST.get('episode_id'))
		context 		= {
			"course":course,
			"courseEpisodes":courseEpisodes,
			"currentPlay":currentPlay
		}
		return render(request, "lesson-page.html", context)

	context         = {
		"course":course,
		"courseEpisodes":courseEpisodes,
		"currentPlay":currentPlay
	}
	return render(request, 'lesson-page.html', context)


@login_required
def uploadCourse(request):

	if request.method == 'POST':
		try:
			getImage  		= request.FILES.get('c-image')
			getTitle   		= request.POST.get('c-title')
			getLanguage   	= request.POST.get('c-language')
			getLength   	= request.POST.get('c-length')
			getDescription  = request.POST.get('c-description')
			getFree  		= request.POST.get('c-free')
			getPrice   		= request.POST.get('c-price')
			getDiscount  	= request.POST.get('c-discount')

			try:
				if getFree:
					course 		= Courses.objects.create(
									title=getTitle, description=getDescription,
									author=request.user, language=getLanguage,
									course_length=getLength, free_price=True, image=getImage,
									price=getPrice, discount_price=getDiscount,
									)
				else: 
					course 		= Courses.objects.create(
									title=getTitle, description=getDescription,
									author=request.user, language=getLanguage,
									course_length=getLength, free_price=False, image=getImage,
									price=getPrice, discount_price=getDiscount
									)
			except:
				if getFree:
					course 		= Courses.objects.create(
									title=getTitle, description=getDescription,
									author=request.user, language=getLanguage,
									course_length=getLength, free_price=True, image=getImage,
									price=getPrice
									)
				else: 
					course 		= Courses.objects.create(
									title=getTitle, description=getDescription,
									author=request.user, language=getLanguage,
									course_length=getLength, free_price=False, image=getImage,
									price=getPrice
									)
				
			messages.success(request, "Course uploaded successfully")
			return redirect(reverse('courses:upload-episodes', kwargs={
				'pk':course.id
				}))

		except Exception as e:
			messages.error(request, "Error occured "+str(e))
			return redirect('courses:upload-course')

	return render(request, 'upload-course.html')


@login_required
def uploadEpisodes(request, pk):
	if request.method == 'POST':
		try:
			getCourse 		= Courses.objects.get(id=pk)
			getTitle   	= request.POST.get('e-title')
			getFile  	= request.FILES.get('e-file')
			getDescription = request.POST.get('e-description')

			episode 	= Episode.objects.create(
								title=getTitle, file=getFile, 
								course=getCourse, description=getDescription
								)
			messages.success(request, 'Episode uploaded for course successfully')
			return redirect(reverse('courses:upload-episodes', kwargs={
				'pk':pk
				}))		

		except Exception as e:
			messages.error(request, "Error occured "+ str(e))
			return redirect(reverse('courses:upload-episodes', kwargs={
				'pk':pk
				}))

	return render(request, 'upload-episodes.html')

courses/templates/checkout-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    
    <title>iGET | Checkout</title>
    <!-- BOOTSTRAP CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="./checkout.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/105e5e9017.js" crossorigin="anonymous"></script>

        <style>
            @import url('https://fonts.googleapis.com/css?family=Montserrat:400,700&display=swap');

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    list-style: none;
    font-family: 'Montserrat', sans-serif
}

body {
    background-color: #3ecc6d
}

.container {
    margin: 20px auto;
    width: 800px;
    padding: 30px
}

.card.box1 {
    width: 350px;
    height: 500px;
    background-color: #3ecc6d;
    color: #baf0c3;
    border-radius: 0
}

.card.box2 {
    width: 450px;
    height: 580px;
    background-color: #ffffff;
    border-radius: 0
}

.text {
    font-size: 13px
}

.box2 .btn.btn-primary.bar {
    width: 20px;
    background-color: transparent;
    border: none;
    color: #3ecc6d
}

.box2 .btn.btn-primary.bar:hover {
    color: #baf0c3
}

.box1 .btn.btn-primary {
    background-color: #57c97d;
    width: 45px;
    height: 45px;
    display: flex;
    justify-content: center;
    align-items: center;
    border: 1px solid #ddd
}

.box1 .btn.btn-primary:hover {
    background-color: #f6f8f7;
    color: #57c97d
}

.btn.btn-success {
    width: 40px;
    height: 40px;
    border-radius: 50%;
    background-color: #ddd;
    color: black;
    display: flex;
    justify-content: center;
    align-items: center;
    border: none
}

.nav.nav-tabs {
    border: none;
    border-bottom: 2px solid #ddd
}

.nav.nav-tabs .nav-item .nav-link {
    border: none;
    color: black;
    border-bottom: 2px solid transparent;
    font-size: 14px
}

.nav.nav-tabs .nav-item .nav-link:hover {
    border-bottom: 2px solid #3ecc6d;
    color: #05cf48
}

.nav.nav-tabs .nav-item .nav-link.active {
    border: none;
    border-bottom: 2px solid #3ecc6d
}

.form-control {
    border: none;
    border-bottom: 1px solid #ddd;
    box-shadow: none;
    height: 20px;
    font-weight: 600;
    font-size: 14px;
    padding: 15px 0px;
    letter-spacing: 1.5px;
    border-radius: 0
}

.inputWithIcon {
    position: relative
}

img {
    width: 50px;
    height: 20px;
    object-fit: cover
}

.inputWithIcon span {
    position: absolute;
    right: 0px;
    bottom: 9px;
    color: #57c97d;
    cursor: pointer;
    transition: 0.3s;
    font-size: 14px
}

.form-control:focus {
    box-shadow: none;
    border-bottom: 1px solid #ddd
}

.btn-outline-primary {
    color: black;
    background-color: #ddd;
    border: 1px solid #ddd
}

.btn-outline-primary:hover {
    background-color: #05cf48;
    border: 1px solid #ddd
}

.btn-check:active+.btn-outline-primary,
.btn-check:checked+.btn-outline-primary,
.btn-outline-primary.active,
.btn-outline-primary.dropdown-toggle.show,
.btn-outline-primary:active {
    color: #baf0c3;
    background-color: #3ecc6d;
    box-shadow: none;
    border: 1px solid #ddd
}

.btn-group>.btn-group:not(:last-child)>.btn,
.btn-group>.btn:not(:last-child):not(.dropdown-toggle),
.btn-group>.btn-group:not(:first-child)>.btn,
.btn-group>.btn:nth-child(n+3),
.btn-group>:not(.btn-check)+.btn {
    border-radius: 50px;
    margin-right: 20px
}

form {
    font-size: 14px
}

form .btn.btn-primary {
    width: 100%;
    height: 45px;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    background-color: #3ecc6d;
    border: 1px solid #ddd
}

form .btn.btn-primary:hover {
    background-color: #05cf48
}

@media (max-width:750px) {
    .container {
        padding: 10px;
        width: 100%
    }

    .text-green {
        font-size: 14px
    }

    .card.box1,
    .card.box2 {
        width: 100%
    }

    .nav.nav-tabs .nav-item .nav-link {
        font-size: 12px
    }
}
        </style>

</head>
<body>
    <div class="container bg-light d-md-flex align-items-center">
        <div class="card box1 shadow-sm p-md-5 p-md-5 p-4">
            <div class="fw-bolder mb-4"><span class="fas fa-dollar-sign"></span><span class="ps-1">iGet Ensures Secured Payment</span></div>
            <div class="d-flex flex-column">
                <div class="d-flex align-items-center justify-content-between text"> <span class="">Commission</span> <span class="fas fa-dollar-sign" style="text-decoration: line-through;"><span class="ps-1">1.59</span></span> </div>
                <div class="d-flex align-items-center justify-content-between text mb-4"> <span>Total</span> <span class="fas fa-dollar-sign"><span class="ps-1">600.99</span></span> </div>
                <div class="border-bottom mb-4"></div>
                <div class="d-flex flex-column mb-4"> <span class="far fa-file-alt text"><span class="ps-2">Invoice ID:</span></span> <span class="ps-3">SN8478042099</span> </div>
                <div class="d-flex flex-column mb-5"> <span class="far fa-calendar-alt text"><span class="ps-2">Date Of Payment</span></span> <span class="ps-3">22nd November,2021</span> </div>
                <div class="d-flex align-items-center justify-content-between text mt-5">
                    <div class="d-flex flex-column text">Make Enquiries<span>
                        24/7 Live Customer Support
                    </span> </div>
                    <div class="btn btn-primary rounded-circle"><span class="fas fa-comment-alt"></span></div>
                </div>
            </div>
        </div>
        <div class="card box2 shadow-sm">
           
            <div class="d-flex align-items-center justify-content-between p-md-5 p-4"> <span class="h5 fw-bold m-0">Payment methods</span>
                <div class="btn btn-primary bar"><span class="fas fa-bars"></span></div>
            </div>
            <ul class="nav nav-tabs mb-3 px-md-4 px-2">
                <li class="nav-item"> <a class="nav-link px-2 active" aria-current="page" href="#">Credit Card</a> </li>
                <li class="nav-item"> <a class="nav-link px-2" href="#">Mobile Payment</a> </li>
                <li class="nav-item ms-auto"> <a class="nav-link px-2" href="#">+ More</a> </li>
            </ul>

            <form action="">
                <div class="row">
                    <div class="col-12 mt-3">
                        <div class="d-flex flex-column px-md-5 px-4 mb-4"> <span>Credit Card</span>
                            <div class="inputWithIcon"> <input class="form-control" type="text" placeholder="**** **** **** ****"> <span class=""> <img src="https://www.freepnglogos.com/uploads/mastercard-png/mastercard-logo-logok-15.png" alt=""></span> </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="d-flex flex-column ps-md-5 px-md-0 px-4 mb-4"> <span>Expiration<span class="ps-1">Date</span></span>
                            <div class="inputWithIcon"> <input type="date" class="form-control" placeholder="05/20"> </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="d-flex flex-column pe-md-5 px-md-0 px-4 mb-4"> <span>Code CVV</span>
                            <div class="inputWithIcon"> <input type="password" class="form-control" placeholder="123"> <span class="fas fa-lock"></span> </div>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="d-flex flex-column px-md-5 px-4 mb-4"> <span>Name</span>
                            <div class="inputWithIcon"> <input class="form-control text-uppercase" type="text" placeholder="Team Cridad"> <span class="far fa-user"></span> </div>
                        </div>
                    </div>
                    <div class="col-12 px-md-5 px-4 mt-3">
                        <a href="{% url 'cart:pay-btn' %}" style="text-decoration:none">
                            <div class="btn btn-primary w-100">Pay ${{objects.get_total}}</div>
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</body>
</html>

courses/templates/edit-profile.html
{% extends 'base.html' %}
{% block title %} My Account {% endblock %}

{% load static %} 
{% block content %}
      <div class="breadcrumb-section">
        <div class="container">
          <div class="row">
            <header class="entry-header">
              <h1 class="entry-title">Edit Profile</h1>
            </header>
          </div> 
        </div>
      </div>
      <div class="page-spacer clearfix">
        <div id="primary" class="content-area">
          <div class="container">
            <div class="row">
              <main id="main" class="site-main col-xs-12">
                <div class="col-xs-12 col-sm-10 register-form edit-profile form clearfix">
                  <h3>Edit Profile</h3>
                  <form name="loginform" id="student-settings" class="student-settings" method="post">
                    <label>First Name <input name="first-name" value="" placeholder="{{request.user.first_name}}" type="text"></label>
                    <label>Last Name <input name="last-name" value="" placeholder="{{request.user.last_name}}" type="text"></label>
                    <label>Email <input name="email" value="" placeholder="{{request.user.email}}" type="text"></label>
                    <label>User Name <input name="username" value="{{request.user.username}}" disabled="disabled" type="text"></label>
                    <label>Password <input name="password" value="" placeholder="Won't change if empty." type="password"> </label>
                    <label>Confirm Password: <input name="confirm-password" value="" type="password"></label>
                    <input name="submit" class="btn btn-default pull-right" value="Save Changes" type="submit"><br><br>
                  </form>
                </div>

                <div class="col-xs-12 col-sm-10 register-form edit-profile form clearfix">
                  <h3>Edit Address</h3>
                  <form name="loginform" id="student-settings" class="student-settings" method="post">
                    <label>First Name <input name="first-name" value="" placeholder="{{request.user.first_name}}" type="text"></label>
                    <label>Last Name <input name="last-name" value="" placeholder="{{request.user.last_name}}" type="text"></label>
                    <label>Email <input name="email" value="" placeholder="{{request.user.email}}" type="text"></label>
                    <label>User Name <input name="username" value="{{request.user.username}}" disabled="disabled" type="text"></label>
                    <label>Password <input name="password" value="" placeholder="Won't change if empty." type="password"> </label>
                    <label>Confirm Password: <input name="confirm-password" value="" type="password"></label>
                    <input name="submit" class="btn btn-default pull-right" value="Save Changes" type="submit">
                  </form>
                </div>
                
              </main>
            </div> 
          </div> 
        </div>
      </div>
      <section class="call-to-action">
        <div class="container">
          <div class="row">
            <div class="col-xs-12">
              <div class="col-xs-12 col-sm-8">
                <h3>Remaining essentially unchanged.</h3>
                <p>When an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
              </div>
              <a href="edit-profile.html#" class="btn btn-medium btn-default pull-right">Know More <i class="lnr lnr-arrow-right"></i></a>
            </div>
          </div> 
        </div>
      </section> 
     {% endblock %}

courses/templates/events.html
{% extends 'base.html' %}
{% block title %}Registered Courses{% endblock %}
{% block listLessonsActive %} active {% endblock %}
{% load static %} 
{% block content %}


<div class="breadcrumb-section">
  <div class="container">
    <div class="row">
      <header class="entry-header">
        <h1 class="entry-title">Enrolled Courses</h1>
      </header>
    </div> 
  </div>
</div>
<div class="page-spacer clearfix">
  <div id="primary">
    <div class="container">
      <div class="row">
        <main id="main" class="site-main col-xs-12 school-events">
          <!-- Getting all orders -->
          {% for registeredCourse in objects %}
            <!-- Getting one order items -->
            {% for course in registeredCourse.items.all %}
              <div class="col-xs-12 col-sm-4">
              <div class="events">
                <a class="img-thumb"><figure>
                  <img src="{{course.item.image.url}}" alt="" /></figure></a>
                  <div class="events-info">
                    <h3><a>{{course.item.title}}</a></h3>
                    <p class="location" style="font-weight: 600;">Tutor: {{course.item.author}}</p>
                    <p>{{course.item.description|truncatewords:"10"}}</p>
                    <ul class="events-time">
                      <li><span>Aug 25 -27, 2015</span>
                      Date </li>
                      <li><span>09:00 AM</span>
                      Time</li>
                    </ul>
                    <a href="{% url 'courses:lesson' course.item.id %}" class="know-more">Start Lesson<i class="lnr lnr-arrow-right"></i></a>
                  </div>
                </div>
              </div> 
            {% endfor %}
          {% empty %}
            <center>
              <h1>No enrolled course</h1>
            </center>
          {% endfor %}
          </main>
        </div> 
      </div> 
    </div>
  </div> 
  <section class="call-to-action">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="col-xs-12 col-sm-8">
            <h3>Remaining essentially unchanged.</h3>
            <p>When an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
          </div>
          <a href="events.html#" class="btn btn-medium btn-default pull-right">Know More <i class="lnr lnr-arrow-right"></i></a>
        </div>
      </div> 
    </div>
  </section> 
  {% endblock %}

courses/templates/lesson-page.html
{% load static %} 
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Lessons Page</title>
        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="{% static 'styles/reset.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'styles/main.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=0.6">
    </head>
    <body>
        <div class="wrapper">
            
            <div class="main-wrapper">
                <div class="left"></div>
                <main>
                    <div class="main__video">
                        <div class="main__video-container">
                            <video controls width="565" height="315" src="{{currentPlay.file.url}}" autoplay></video>
                                
                        </div>
                        <div class="main__description">
                            <h1 style="font-size:20px;font-weight: 500">{{course.title}}</h1><br>
                            <p>Tutor: {{course.author}} - 290,399 views</p>
                        </div>
                        <div class="main__sub-description" style="justify-content: start;">
                            <p>
                            <b style="font-size:18px;font-weight:500">Episode Description</b><br>
                            {{currentPlay.description}}
                            </p>
                        </div>
                        
                    </div>
                    <aside class="aside">
                        <div class="aside__top-container">
                            <p>Episodes</p>
                            <a href="{% url 'courses:list-lessons' %}">BACK</a>
                        </div>
                       {% for episode in courseEpisodes %}
                       <div 
                       {% if episode.id == currentPlay.id  %}
                        style="background:ghostwhite; border-left: 5px solid red;padding: 1%;"
                       {% endif %}
                        >
                        <form method="POST" id="my_form">
                            {% csrf_token %}
                            <input style="display:none" type="text" value="{{episode.id}}" name="episode_id">
                            <a style="height: 100px;display:flex; flex-direction:row; color:black;text-decoration:none;">
                            <img  class="aside__video" src="{{course.image.url}}" alt="Next video">
                            <div style="padding:2%"></div>
                            <div style="display: flex;flex-direction: column;justify-content: space-between;">
                                <p>{{episode.description|truncatewords:"15"}}</p>
                                <button type="submit" style="width:120px;height: 30px;background:orangered;color:white;border-radius: 10px;font-weight: 600;">
                                        
                                    {% if episode.id == currentPlay.id %}
                                        Playing
                                    {% else %}
                                        Play
                                    {% endif %}
                                

                                </button>
                            </div>
                            </a>
                        </form>
                        </div>
                        <br>
                        {% empty %}
                        
                            <h2 style="font-weight:500; font-size:30px; font-family: poppins;">No episodes</h2>
                        
                        {% endfor %}
                       
                        
                        
                    </aside>

                  

                </main>
            </div>
        </div>
    </body>
</html>

courses/templates/under-construction.html
<!DOCTYPE html>
<html lang="en">

<!--under-construction23:53  -->
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>Coming Soon Page</title>


<!--[if lt IE 9]>
  <script src="js/html5shiv.min.js"></script>
  <script src="js/respond.min.js"></script>
<![endif]-->

<link rel="shortcut icon" href="images/favicon.png" />

<link href="css/comming-soon.css" rel="stylesheet">
</head>
<body class="page-under-construction">
<div class=" construction">
<h1>Coming Soon...</h1>
<h4>We are current working on website. We hope to be back online shortly.</h4>
<a href="under-construction.html#bottom"><i class="arrow-down"></i></a>
<div class="countdown" id="countDown" data-end-date='2017-04-21 00:00:00'>
<span class="days">{dn}<small>{dl}</small></span>
<span class="hours">{hn}<small>{hl}</small></span>
<span class="min">{mn}<small>{ml}</small></span>
<span class="sec">{sn}<small>{sl}</small></span>
</div>
<div class="newsletter">
<h3>Get Notified</h3>
<form data-name="Sign up Form" method="post" class="signup-form" id="signup">
<input type="email" placeholder="Your email address" class="" name="email">
<button class="btn btn-orange btn-medium" value="Sign up" type="submit">Signup <i class="lnr lnr-arrow-right"></i></button>
</form>
</div>
<p class="copyright">Copyright 2009 - 2016 Educations. All Rights Reserved</p>
</div>

<script src="js/jquery.min.js"></script>

<script type="text/javascript" src="vendor/countdown/js/jquery.plugin.min.js"></script>
<script type="text/javascript" src="vendor/countdown/js/jquery.countdown.min.js"></script>
<script type="text/javascript">

	"use strict";
	
	 if( jQuery('#countDown').length) {
			var dateStr = jQuery( '#countDown').data( 'end-date' );
			var a=dateStr.split(' ');
			var d=a[0].split('-');
			var t=a[1].split(':');
			var date1 = new Date(d[0],(d[1]-1),d[2],t[0],t[1],t[2]);		
			jQuery('#countDown').countdown({until: date1, labels: ['Years', 'Months', 'Weeks', 'Days', 'Hours', 'Minutes', 'Seconds'],  labels1: ['Year', 'Month', 'Week', 'Day', 'Hour', 'Minute', 'Second'], timezone: 0, layout: jQuery('#countDown').html() });
	  }
</script>
</body>

<!--under-construction23:54  -->
</html>